[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Définissez ceci dans l'UI Netlify une fois le backend Render en ligne
  # VITE_API_URL = "https://votre-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
